using System;
using System.Collections.Generic;
using UnityEngine;

namespace HeartopiaMod
{
    // Roaming collectable radar — Oak-Oak (橡走走) and the Flawless Fluorite mine (特工M, the
    // fluorite-carrying mole). Both relocate every game day, and the game gives no hint.
    //
    // Mechanic (cn tables + ilspy dumps, 2026-08-04). They are "advanced collectables"
    // (EntityType.advcollectable): Entity 42001 / 42002, Advcollectable prefabs
    // p_advcollectable_oakee_skeleton / p_advcollectable_agentm_skeleton, AdvCollect.itemTypeId
    // 401 / 402, dropping 40006 Roaming Oak Timber / 40026 Flawless Fluorite. They are the ONLY
    // two MapDynamicResource rows (ids 1 and 2) with mapPosId = 0 and a non-empty mapPosConfig
    // ([1,1] / [1,2]) — "no fixed point, take one from the pool"; every other dynamic object in
    // that 643-row table names a concrete mapPosId. Unlock gates: PlayerFeatureOpen[23] (高级树)
    // and [24] (高级矿).
    //
    // WHERE TODAY'S SPOT IS DECIDED: on the SERVER. The per-day point list lives in
    // MapResourceRefreshConfig (EcsClient/.../Scriptable — configSetDate + MapResourceData
    // {itemTypeId, refreshType day/week/month, mapResourceNum, mapResourceList}, header comment
    // "two years of config data generated by default"), which is declared in the shared data
    // schema but is NOT a field of GameLevelBaseConfig/SceneConfig and is referenced by nothing
    // client-side. TableMapRareResourceConfig is stripped to a bare `id` column in the client
    // build and is likewise dead. Refresh bookkeeping is server-persisted per player
    // (PlayerMapResourceFreshSaveComponent [Persistent("PlyRF")] {Category, RefreshConfigId,
    // LastUpDateTime}); the day boundary is 06:00 (DynamicMapItemService.GetColdEndTime treats
    // totalColdTime == 86400 as "next 06:00"). So nothing client-side predicts the spot — the
    // position only exists once the server streams the spawned entity.
    //
    // HOW WE FIND IT — Entities.GetComponents<CollectableAdvancedTreeComponent> /
    // <CollectableAdvancedStoneComponent> (AuraMono, the proven TryAuraMonoGetComponentObjects
    // helper): identity is the component CLASS itself, so it holds regardless of what the sibling
    // CollectableObjectComponent made of its ICollectableObject proxy. Position off the component's
    // `entity`, cooldown off the `_collectable` sibling's `inCold` (true once today's harvest is
    // done — 86400 s). Cheap: a handful of components.
    //
    // Why not a DataCenter walk: the DataCenter side of these entities is
    // AdvancedTreeComponentData / AdvancedStoneComponentData, reachable only through
    // TryGetEntityIdsWithComponentType<T> / TryGetComponentData<T> — generics over a STRUCT.
    // Inflating those under AuraMono is the documented crash trap in this codebase (see
    // HeartopiaComplete.Fishing.cs:610) and the managed path is dead (no EcsClient/XDT* in
    // interop). Generic inflate is safe for CLASS type arguments, which is exactly what the view
    // component scan above uses — same information, proven channel.
    //
    // ⛔ The obvious cheaper route — filtering the radar's shared collectable snapshot
    // (RefreshCollectableScan -> mapResEntities) on ProduceId 401/402 — DOES NOT WORK and was
    // removed after the 2026-08-04 live test: with Oak-Oak standing right next to the player and
    // the snapshot holding 50 collectables, `matches` stayed 0 on every pass while the direct scan
    // reported 1. These entities never survive into the snapshot: their StaticId is always 0
    // (AddAdvancedCollectableEntityData adds no StaticEntityData) and their itemTypeID reads 0, so
    // RefreshCollectableScan's "staticId <= 0 && produceId <= 0 -> drop" rule discards them. Do not
    // re-add that filter.
    //
    // ⛔ RANGE IS NOT EXTENDABLE FROM THE CLIENT — a second, long-range source over
    // Entities.GetComponents<LevelEntityComponent> (matching `_viewEntityArg.resId.resId` against
    // 42001/42002, on the theory that the streaming/LOD driver outlives the gather components) was
    // built and MEASURED on 2026-08-04: `level total=868 walked=868 matched=0 readFails=0` on the
    // very pass where the gather scan reported the object. Whole population swept, identity reads
    // healthy, still absent — these entities are skeleton-based (AvatarComponentData +
    // p_advcollectable_*_skeleton) and simply carry no LevelEntityComponent. It was removed rather
    // than left in as dead weight. More importantly the same run showed the gather component
    // MISSING ENTIRELY at range (not merely unspawned), i.e. the whole view entity does not exist
    // out there — the limit is the server's AOI, not client-side culling, so no view-layer scan can
    // beat it. Do not re-litigate this without new evidence about the server's send scope.
    //
    // STREAMING: near the object the components still come and go with significance — the live log
    // alternated 1/0/1/0 while standing still, which blinked the marker every other radar pass. So a
    // located position is REMEMBERED for the world session (the Sanrio placed-machine precedent: the
    // object does not move within a day, only its view streams out) and re-emitted while the scan
    // misses. It is forgotten only after RoamingCacheForgetSeconds without a confirmation while the
    // player is inside RoamingCacheProbeRadius — the first cut (6 consecutive misses within 60 m)
    // fired on ordinary churn and threw away a perfectly good spot.
    //
    // RoamingRadarDiag logs the scan counts whenever they change (throttled): -1 = that target's
    // toggle is off, or its class/pinning was unavailable; 0 = the scan ran and found nothing.
    public partial class HeartopiaComplete
    {
        // Radar toggles — session-only, like every other per-resource radar flag.
        private bool showOakOakRadar = false;
        private bool showFluoriteRadar = false;

        // One "located" toast per world session per target (a daily unique is worth announcing;
        // ordinary resources are not). Keyed to the world epoch so a level change re-arms it.
        private int roamingOakNotifiedEpoch = -1;
        private int roamingFluoriteNotifiedEpoch = -1;

        // Embedded-Mono view component classes (image lifetime — raw IntPtr is fine; re-resolved
        // every pass until the XDTLevelAndEntity image is up).
        private IntPtr roamingOakComponentClass = IntPtr.Zero;
        private IntPtr roamingFluoriteComponentClass = IntPtr.Zero;

        private struct RoamingCollectableHit
        {
            public Vector3 Position;
            public bool IsOak;
            public bool OnCooldown;
            public bool ColdKnown;    // OnCooldown came from a readable live inCold (not a guess / memory)
            public uint NetId;        // 0 when the entity's netId could not be read
        }

        private readonly List<RoamingCollectableHit> roamingHits = new List<RoamingCollectableHit>(4);

        // Remembered position per target (see the file header — the view component streams out
        // while the object itself stays put for the rest of the game day).
        private struct RoamingRememberedSpot
        {
            public bool Known;
            public Vector3 Position;
            public bool OnCooldown;
            public float LastSeenAt; // Time.unscaledTime of the last live confirmation
            public uint NetId;       // last netId seen at this spot, 0 if never read
        }

        private RoamingRememberedSpot roamingOakSpot;
        private RoamingRememberedSpot roamingFluoriteSpot;
        private int roamingSpotEpoch = -1;

        // Forgetting a remembered spot. The first cut (6 consecutive misses within 60 m) fired on
        // ordinary streaming churn in the live log — "gone from its remembered spot" while the
        // object was still there — so this is now a TIME rule at point-blank range: only when the
        // player has been essentially on top of the spot and nothing has confirmed it for a full
        // dry spell. A radar pass count is the wrong unit (its rate varies with the scan throttle).
        private const float RoamingCacheProbeRadius = 25f;
        private const float RoamingCacheForgetSeconds = 45f;

        // Diagnostics: one line whenever the per-source counts change (never per frame).
        private string roamingDiagSignature = string.Empty;
        private float roamingNextDiagAt = -999f;

        // Radar markers for the two daily-roaming advanced collectables: scan live, fold into the
        // remembered spots (see the file header), then mark whatever is inside the radar range.
        private void ScanRoamingCollectables(Vector3 origin, Material line, Material fill)
        {
            bool wantOak = this.showOakOakRadar;
            bool wantFluorite = this.showFluoriteRadar;
            if (!wantOak && !wantFluorite)
            {
                return;
            }

            if (line == null || fill == null)
            {
                return;
            }

            // A world change invalidates every remembered position (new level, and the daily
            // re-place happens across a relog anyway).
            int epoch = HeartopiaComplete.AuraMonoWorldEpoch;
            if (this.roamingSpotEpoch != epoch)
            {
                this.roamingSpotEpoch = epoch;
                this.roamingOakSpot = default(RoamingRememberedSpot);
                this.roamingFluoriteSpot = default(RoamingRememberedSpot);
            }

            this.roamingHits.Clear();

            int oakLive = wantOak
                ? this.CollectRoamingAdvCollectables(ref this.roamingOakComponentClass,
                    "XDTLevelAndEntity.Gameplay.Component.Gather.CollectableAdvancedTreeComponent",
                    "XDTLevelAndEntity.GamePlay.Component.Gather.CollectableAdvancedTreeComponent",
                    true)
                : -1;
            int fluoriteLive = wantFluorite
                ? this.CollectRoamingAdvCollectables(ref this.roamingFluoriteComponentClass,
                    "XDTLevelAndEntity.Gameplay.Component.Gather.CollectableAdvancedStoneComponent",
                    "XDTLevelAndEntity.GamePlay.Component.Gather.CollectableAdvancedStoneComponent",
                    false)
                : -1;

            // Fold this pass into the remembered spots, then top the hit list back up from them so
            // a streamed-out object keeps its marker instead of blinking.
            if (wantOak)
            {
                this.UpdateRoamingSpot(ref this.roamingOakSpot, true, origin);
            }
            if (wantFluorite)
            {
                this.UpdateRoamingSpot(ref this.roamingFluoriteSpot, false, origin);
            }

            this.LogRoamingRadarDiag(oakLive, fluoriteLive);

            bool oakMarked = false;
            bool fluoriteMarked = false;

            // DELIBERATE EXCEPTION to the radar's max-distance slider: these two are once-a-day
            // uniques and finding them is the whole point of the feature, so a hit is always
            // marked. It matters for the REMEMBERED spot — walk away from a located object and the
            // slider (75 m by default) would hide the very marker you went looking for. At most two
            // markers, so there is no clutter argument either.
            for (int i = 0; i < this.roamingHits.Count; i++)
            {
                RoamingCollectableHit hit = this.roamingHits[i];
                // The live component's inCold OR a persisted long cooldown at this spot. The
                // latch alone misses two ways: collect-and-drive-off before a scan pass reads
                // inCold=true, and any restart (the remembered spot is in-memory). The ledger
                // rows for these two carry the next-06:00 end, so the marker stays a cooldown
                // one — and the farm's candidate filter skips cooldown markers, which is what
                // keeps a collected daily from being re-targeted.
                //
                // ⚠️ A READABLE LIVE inCold OUTRANKS THE POSITIONAL LEDGER. These two get a new netId
                // every session and often come back to the SAME spot, so the positional row of an
                // earlier session's entity lands exactly on today's one. Measured 2026-09-24: the
                // fluorite (netId 20012) read inCold=false and the server sent end=0 for it, while a
                // disk row of netId 20062 at the same position (0.05 m) still claimed a cooldown —
                // the marker went cooldown and the map sync skipped it. The ledger is for what we
                // cannot see; once the component in front of us answers, it has the last word
                // (the same rule as the farm's "component refutes a stored cooldown").
                bool verdictCold = this.IsRoamingHitColdByVerdict(hit);
                bool ledgerCold = !hit.ColdKnown
                    && (this.TryGetPersistedColdAtPosition(hit.Position, out _) || verdictCold);
                if (hit.ColdKnown && !hit.OnCooldown)
                {
                    this.DropRefutedRoamingColdRows(hit);
                }
                if (hit.IsOak)
                {
                    this.CreateMarker(hit.Position, (hit.OnCooldown || ledgerCold) ? "oakoak_cooldown" : "oakoak", line, fill, null);
                    oakMarked = true;
                }
                else
                {
                    this.CreateMarker(hit.Position, (hit.OnCooldown || ledgerCold) ? "fluorite_cooldown" : "fluorite", line, fill, null);
                    fluoriteMarked = true;
                }
            }

            if (oakMarked && this.roamingOakNotifiedEpoch != epoch)
            {
                this.roamingOakNotifiedEpoch = epoch;
                this.AddMenuNotification(this.L("Oak-Oak located!"), new Color(0.92f, 0.76f, 0.35f));
                ModLogger.Msg("[RoamingRadar] Oak-Oak located.");
            }

            if (fluoriteMarked && this.roamingFluoriteNotifiedEpoch != epoch)
            {
                this.roamingFluoriteNotifiedEpoch = epoch;
                this.AddMenuNotification(this.L("Flawless Fluorite located!"), new Color(0.74f, 0.56f, 1f));
                ModLogger.Msg("[RoamingRadar] Flawless Fluorite located.");
            }
        }

        // Entities.GetComponents<T> over one advanced-collectable view component class -> world
        // positions. Returns the raw component count, or -1 when the scan could not run at all
        // (class unresolved / infra not ready) so the diagnostic can tell "none spawned" from
        // "never looked". Pin discipline mirrors RefreshCollectableScan: the component list is
        // pinned by the helper, each derived entity is pinned across its own reads (member reads
        // allocate, and the sgen GC moves anything unpinned).
        private int CollectRoamingAdvCollectables(ref IntPtr classPtr, string typeName, string altTypeName, bool isOak)
        {
            if (classPtr == IntPtr.Zero)
            {
                // Retry every pass until the image is loaded (never latch on the first miss).
                classPtr = this.FindAuraMonoClassByFullName(typeName);
                if (classPtr == IntPtr.Zero)
                {
                    classPtr = this.FindAuraMonoClassByFullName(altTypeName);
                }
                if (classPtr == IntPtr.Zero)
                {
                    return -1;
                }
            }

            // Fail closed without the gchandle exports: an unpinned enumeration walks movable
            // sgen memory (memory: auramono-pinning-fail-closed).
            if (!AuraMonoPinningAvailable)
            {
                return -1;
            }

            List<uint> compPins = new List<uint>();
            try
            {
                // Returns false for an EMPTY list too — that is the normal "not spawned / not
                // streamed" case, reported as 0 rather than as a failure.
                if (!this.TryAuraMonoGetComponentObjects(classPtr, out List<IntPtr> components, compPins)
                    || components == null)
                {
                    return 0;
                }

                for (int i = 0; i < components.Count; i++)
                {
                    IntPtr comp = components[i];
                    if (comp == IntPtr.Zero
                        || !this.TryGetMonoObjectMember(comp, "entity", out IntPtr entityObj)
                        || entityObj == IntPtr.Zero)
                    {
                        continue;
                    }

                    uint entityPin = AuraMonoPinNew(entityObj);
                    try
                    {
                        if (!this.TryGetMonoVector3Member(entityObj, "position", out Vector3 pos))
                        {
                            continue;
                        }

                        // The netId is what the cold verdicts are keyed by; read it here, while the
                        // entity is pinned, so the marker can be judged by verdict below.
                        uint netId = 0;
                        this.TryGetMonoUInt32Member(entityObj, "netId", out netId);

                        // Cooldown lives on the sibling CollectableObjectComponent the advanced
                        // component caches in _collectable; unreadable -> treat as ready (the
                        // marker is the point, the cooldown tint is a bonus).
                        bool onCooldown = false;
                        bool coldKnown = false;
                        if (this.TryGetMonoObjectMember(comp, "_collectable", out IntPtr collectableObj)
                            && collectableObj != IntPtr.Zero)
                        {
                            uint collectablePin = AuraMonoPinNew(collectableObj);
                            try
                            {
                                coldKnown = this.TryGetMonoBoolMember(collectableObj, "inCold", out bool inCold);
                                onCooldown = coldKnown && inCold;
                            }
                            finally
                            {
                                AuraMonoPinFree(collectablePin);
                            }
                        }

                        this.AddRoamingHit(pos, isOak, onCooldown, netId, coldKnown);
                    }
                    finally
                    {
                        AuraMonoPinFree(entityPin);
                    }
                }

                return components.Count;
            }
            finally
            {
                FreeAuraMonoPins(compPins);
            }
        }

        // Fold this pass's live result for one target into its remembered spot, and make sure the
        // hit list carries a position whenever we know one.
        //  - live hit  -> refresh the spot, clear the miss streak;
        //  - live miss -> re-emit the remembered position; count the miss only when the player is
        //                 close enough that the object SHOULD have streamed in, and forget it once
        //                 that has held for RoamingCacheMissesToForget passes.
        private void UpdateRoamingSpot(ref RoamingRememberedSpot spot, bool isOak, Vector3 origin)
        {
            for (int i = 0; i < this.roamingHits.Count; i++)
            {
                RoamingCollectableHit hit = this.roamingHits[i];
                if (hit.IsOak != isOak)
                {
                    continue;
                }

                spot.Known = true;
                spot.Position = hit.Position;
                spot.OnCooldown = hit.OnCooldown;
                spot.LastSeenAt = Time.unscaledTime;
                if (hit.NetId != 0)
                {
                    spot.NetId = hit.NetId;
                }

                return;
            }

            if (!spot.Known)
            {
                return;
            }

            if ((spot.Position - origin).sqrMagnitude <= RoamingCacheProbeRadius * RoamingCacheProbeRadius
                && Time.unscaledTime - spot.LastSeenAt >= RoamingCacheForgetSeconds)
            {
                spot = default(RoamingRememberedSpot);
                ModLogger.Msg("[RoamingRadar] " + (isOak ? "Oak-Oak" : "Flawless Fluorite")
                    + " gone from its remembered spot (moved or collected) — forgetting it.");
                return;
            }

            this.AddRoamingHit(spot.Position, isOak, spot.OnCooldown, spot.NetId, false);
        }

        // The live component just called this spot ready: delete every stored cooldown within the
        // positional-lookup radius that belongs to a DIFFERENT (earlier-session) netId, both the
        // disk row and its seeded in-memory copy, so neither the radar nor the farm's marker
        // filter keeps treating today's object as collected.
        private void DropRefutedRoamingColdRows(RoamingCollectableHit hit)
        {
            List<uint> refuted = null;
            foreach (var pair in this.coldLedgerPersisted)
            {
                if (pair.Key == hit.NetId)
                {
                    continue;
                }

                Vector3 p = pair.Value.Position;
                float dx = p.x - hit.Position.x;
                float dz = p.z - hit.Position.z;
                if (p.sqrMagnitude >= 0.01f && (dx * dx) + (dz * dz) <= 2.25f)
                {
                    (refuted = refuted ?? new List<uint>()).Add(pair.Key);
                }
            }

            if (refuted == null)
            {
                return;
            }

            for (int i = 0; i < refuted.Count; i++)
            {
                this.coldLedgerPersisted.Remove(refuted[i]);
                this.collectColdByNetId.Remove(refuted[i]);
            }

            this.coldLedgerDirty = true;
            ModLogger.Msg("[RoamingRadar] " + (hit.IsOak ? "Oak-Oak" : "Flawless Fluorite") + " netId " + hit.NetId
                + " reads ready: dropped " + refuted.Count + " stale cooldown row(s) of an earlier session at the same spot.");
        }

        // ⭐ THE VERDICT FOR THIS ENTITY, BY NETID — THE POSITIONAL LEDGER LOOKUP MISSES THESE TWO.
        //
        // Measured 2026-09-13: Oak-Oak drawn as available at (61.4, 21.1, 94.1), 152 m from the
        // player, while the mod held a verdict for netId 20061 ending at the next day boundary —
        // received at unscaledTime 1662, the very tick the Oak-Oak streamed in (the spot's
        // LastSeenAt was 1662.9; the Fluorite's 1598 vs 1600.5 matched the same way). The marker
        // could not see it for two reasons stacked:
        //   * the live inCold read treats "unreadable" as ready, on purpose;
        //   * the ledger lookup is BY POSITION, and this netId's persisted row carried (0,0,0):
        //     an advanced collectable is not in the resource scan the ledger takes positions from.
        // The verdict itself was silent in the log as well — the CollectColdEvent line goes through
        // AutoFarmLog, which was off — so nothing anywhere said the tree was spent.
        //
        // So ask the verdicts by the entity's own netId, and while here give the persisted row the
        // position it never had, so the positional lookup (and the farm's marker filter, which uses
        // it) works for this spot after a restart too.
        private bool IsRoamingHitColdByVerdict(RoamingCollectableHit hit)
        {
            if (hit.NetId == 0)
            {
                return false;
            }

            long now = NowUnixMs();
            bool cold = false;
            if (this.collectColdByNetId.TryGetValue(hit.NetId, out CollectColdRecord live) && live.EndUnixMs > now)
            {
                cold = true;
            }

            if (this.coldLedgerPersisted.TryGetValue(hit.NetId, out PersistedColdEntry persisted))
            {
                if (persisted.EndUnixMs > now)
                {
                    cold = true;
                }

                if (persisted.Position == Vector3.zero)
                {
                    persisted.Position = hit.Position;
                    this.coldLedgerPersisted[hit.NetId] = persisted;
                    this.coldLedgerDirty = true;
                    ModLogger.Msg("[RoamingRadar] " + (hit.IsOak ? "Oak-Oak" : "Flawless Fluorite")
                        + " netId " + hit.NetId + ": persisted cooldown row had no position, stamped "
                        + FormatNavMeshVector(hit.Position) + ".");
                }
            }

            return cold;
        }

        // Merge a position into the hit list, deduped within 2 m; a position reported as
        // on-cooldown by any source stays on-cooldown.
        private void AddRoamingHit(Vector3 pos, bool isOak, bool onCooldown, uint netId, bool coldKnown)
        {
            for (int i = 0; i < this.roamingHits.Count; i++)
            {
                RoamingCollectableHit existing = this.roamingHits[i];
                if (existing.IsOak != isOak || (existing.Position - pos).sqrMagnitude > 4f)
                {
                    continue;
                }

                bool changed = false;
                if (onCooldown && !existing.OnCooldown)
                {
                    existing.OnCooldown = true;
                    changed = true;
                }

                if (netId != 0 && existing.NetId == 0)
                {
                    existing.NetId = netId;
                    changed = true;
                }

                if (coldKnown && !existing.ColdKnown)
                {
                    existing.ColdKnown = true;
                    changed = true;
                }

                if (changed)
                {
                    this.roamingHits[i] = existing;
                }

                return;
            }
            this.roamingHits.Add(new RoamingCollectableHit
            {
                Position = pos,
                IsOak = isOak,
                OnCooldown = onCooldown,
                ColdKnown = coldKnown,
                NetId = netId,
            });
        }

        // One log line per CHANGE of the live/remembered counts (throttled), so a "nothing shows
        // up" report is diagnosable without a live session: -1 = the scan never ran (class
        // unresolved / pinning unavailable / toggle off), 0 = ran and found nothing spawned. The
        // 1/0/1/0 alternation this used to reveal is now absorbed by the remembered spots — a
        // steady `marked` with a flickering `live` is the expected healthy shape.
        private void LogRoamingRadarDiag(int oakLive, int fluoriteLive)
        {
            float now = Time.unscaledTime;
            if (now < this.roamingNextDiagAt)
            {
                return;
            }

            string signature = oakLive + "/" + fluoriteLive + "/" + this.roamingHits.Count
                + "/" + (this.roamingOakSpot.Known ? 1 : 0) + (this.roamingFluoriteSpot.Known ? 1 : 0);
            if (string.Equals(signature, this.roamingDiagSignature, StringComparison.Ordinal))
            {
                return;
            }

            this.roamingDiagSignature = signature;
            this.roamingNextDiagAt = now + 5f;
            // scan -1 = that target's toggle is off, or its class/pinning was unavailable.
            ModLogger.Msg("[RoamingRadar] scan oak=" + oakLive + " fluorite=" + fluoriteLive
                + " | remembered oak=" + this.roamingOakSpot.Known + " fluorite=" + this.roamingFluoriteSpot.Known
                + " | marked=" + this.roamingHits.Count);
        }
    }
}
